export const ERROR_HTTP_STATUS: Record<string, number> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  INVALID_CREDENTIALS: 401,
  USER_DISABLED: 403,

  VALIDATION_ERROR: 400,

  UPSTREAM_TIMEOUT: 504,
  UPSTREAM_UNAVAILABLE: 503,
  UPSTREAM_RATE_LIMIT: 429,
  UPSTREAM_ERROR: 502,
  UPSTREAM_INVALID_RESPONSE: 502,

  INITIATIVE_NOT_FOUND: 404,
  INITIATIVE_NOT_ACTIVE: 400,
  INVALID_STATE_TRANSITION: 400,
  USER_NOT_ASSIGNED: 403,
  CONFLICT_VERSION_MISMATCH: 409,

  SESSION_NOT_FOUND: 404,
  SESSION_CLOSED: 400,
  SESSION_ALREADY_CLOSED: 400,
  ITEM_NOT_FOUND: 404,
  ITEM_ALREADY_EXISTS: 409,

  VACATION_NOT_FOUND: 404,
  VACATION_IMMUTABLE: 400,
  VACATION_INVALID_DATES: 400,
  VACATION_OVERLAP: 409,

  TASK_NOT_FOUND: 404,

  INTERNAL_ERROR: 500,
};

export function statusByErrorCode(code: string): number {
  return ERROR_HTTP_STATUS[code] ?? 500;
}
